apiVersion: batch/v1
kind: Job
metadata:
  name: webshop-job
spec:
  template:
    spec:
      containers:
      - name: webshop-job
        image: yash5090/webshop:latest
        ports:
        - containerPort: 8000
      restartPolicy: OnFailure
