apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: webshop
  template:
    metadata:
      labels:
        app: webshop
    spec:
      containers:
        - name: webshop
          image: yash5090/webshop:latest # Replace with the actual image tag
          ports:
            - containerPort: 8000 # Replace with the port your Tetris game listens on
